<div class="container">
    <div class="panel panel-ecustom ui-shadow">
<!--        <div class="panel-heading etitleprin">
            <b> <?php echo 'SEDE: '.($this->_request->session('sede')).' / LOCAL: '.$this->_request->session('nlocal'); ?></b></div>-->
            <div class="panel-body etitle">
                
                <form class="form-signin" role="form" action="<?php echo BASE_URL; ?>index.php/paquete" method="GET" id="frmauladirector" name="frmauladirector">
                    <!--<input type="hidden" name="opcion" id="opcion" value="<?php // echo ""; ?>" />-->                    
                    <!--<input type="hidden" name="txtSede" id="txtSede" value="<?php // echo $this->txtSede; ?>" />-->                    
                    
<div class="row">
        
           <div class="col-xs-12 espace-top espace-bottom buscador">
           <?php if(!isset($this->paquetes_sin_inventariar) or  $this->estado == '8'):?>
           <div class="form-group">
            <label for="sede_oeprativa">Seleccione Sede Operativa</label>
            <select name="" id="sede_operativa" class="form-control">
                <option value="">--Seleccione--</option>
            </select>
        </div>
        
           <div class="form-inline row">
           <div class="text-center">
                <h1 id="caja_value" type="text" placeholder=""></h1>
                
                <a class="btn btn-primary" id="agregar-caja" onclick="agregar_caja()" ><i class="fa fa-plus"></i> GENERAR CAJA NUEVA</a>
           </div>
            </div>
            <hr>
            <?php endif; ?>
           </div>
                    <div class="input-group col-md-12"> 
                              
                        <input id="txtCaja"  name="txtCaja" required class="form-control text-left input-buscador" type="number"  placeholder="Código de Barra Caja" data-length="" value="<?php echo  isset($this->caja) ? $this->caja->COD_CAJA: '';?>">

                        <span class="input-group-btn">
                            <!--<button class="btn btn-primary  input-buscador" type="button" onclick="boton_caja()" >Buscar</button>-->
                            <button class="btn btn-success input-buscador" type="submit" id="buscarcaja" name="buscarcaja">Buscar</button>&nbsp;&nbsp;
                            <?php if(isset($this->paquetes_sin_inventariar) or $this->estado == '7'):    ?>   
                            <button class="btn btn-danger input-buscador" id="quitar-caja" <?php if($this->estado == '7' or $this->estado == '8'): ?> disabled <?php endif; ?> onclick="borrar_caja('<?php echo  isset($this->caja) ? $this->caja->COD_CAJA: ''; ?>')" ><i class="fa fa-minus"></i> ELIMINAR CAJA</button>
                            <?php endif; ?>
                            <button class="btn btn-primary input-buscador" type="button"  <?php if($this->estado == '7' or $this->estado == '8'): ?> disabled <?php endif; ?>data-toggle="modal" data-target="#myModal" >
                                CIERRE DE CAJA</button>
                        </span>
                    </div>
                </div>
           </div>


            <div class="row">
                <div class="col-xs-12 espace-top espace-bottom buscador">
                   
                <div class="input-group">
                        <input id="txtCodPaquete" name="txtCodPaquete" class="form-control text-left input-buscador" <?php if ($this->estado == '7') echo 'readonly="readonly"'; ?>  type="number" placeholder="Pasar Lector de Código de Barra" >
                        <span class="input-group-btn">                            
                            <button class="btn btn-success input-buscador" type="submit" >Buscar</button>
                        </span>
                    </div>
                </div>
            </div>

    <div class="row espacerightleft" >
       
       <?php  if($this->estado == '1'): //1?>
        <div class="row  alert-success2 alert" >
              <div class="row">
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                      
                        <label class="espacetitlebottom etitletit"><b>COD. PAQUETE: </b></label>
                        <label id="dni_id" style="font-size:24px;"><?php echo ($this->paquete) ? $this->paquete->COD_PAQUETE : ''; ?></label>
                    </div>
                </div>                  
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                                  
                        <label class="espacetitlebottom etitletit"><b>MANUAL: </b></label>
                        <label id="dni_id" style="font-size:24px;"><?php echo ($this->paquete) ?  $this->paquete->COD_MANUAL .' - '. $this->paquete->MANUAL : ''; ?></label>
                    </div>
                </div>                      
                <?php 
                $item_cantidad_faltantes=0;
                foreach($this->paquetes_sin_inventariar as $item){
                $item_cantidad_faltantes+=$item->CANTIDAD;}
                
                
                ?>
                  <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                      
                        <label class="espacetitlebottom etitletit"><b>SEDE: </b></label>
                        <label id="dni_id" style="font-size:24px;"><?php echo ($this->paquete) ? $this->paquete->SEDE : ''; ?></label>
                    </div>
                </div>
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                      
                        <label class="espacetitlebottom etitletit"><b>CANT. DE DOCUMENTOS FALTANTES: </b></label>
                        <label id="dni_id" style="font-size:24px;"><?php echo ($this->paquetes_sin_inventariar) ? $item_cantidad_faltantes : ''; ?></label>
                    </div>
                </div>

         </div>
        </div>
       <?php endif; ?>
       <?php if($this->estado == '4'):    ?>   
    <div class="row alert alert-warning">
      
        <div class="col-xs-12 text-center espace-bottom"> ERROR: <b>LA SEDE A LA QUE PERTENECE ES.</b> </div>
        <div class="row">


                          <table class="table">
                               <tr>
                                    <td colspan="2" class="nowrap"> 
                                    <label class="etitletit">
                                <b>COD. PAQUETE :</b> </label>
                                <label id="dni_id"><?php echo ($this->paquete) ? $this->paquete->COD_PAQUETE : ''; ?></label>
                                </td>
                                
                                <tr>
                                    <td colspan="2" class="nowrap"> 
                                    <label class="etitletit">
                                <b>Sede :</b> </label>
                                <label id="dni_id"><?php echo ($this->paquete) ? $this->paquete->SEDE : ''; ?></label>
                                </td>

                                  </tr>
                                </table> 
        </div>
    </div>  
    
    
    <?php endif; ?>
       
       
       <?php  if($this->estado == '2'): //4?>
       <?php if(isset($_GET['txtCodPaquete']) && trim($_GET['txtCodPaquete']) !== "" ) : ?>
        <div class="row alert-danger2 alertrojo" >

            <div class="col-xs-12 text-center espace-bottom"> ERROR : <b>N&Uacute;MERO DE PAQUETE NO ENCONTRADO</b></div>
              <div class="row">
                 
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">
                       
                        <label class="espacetitlebottom etitletit" style="font-size: 32px"><b>CODIGO PAQUETE:</b></label>
                        <label id="dni_id" style="font-size: 32px" ><?php echo $_REQUEST['txtCodPaquete']?></label>
                    </div>
                </div>
                

         </div>
        </div>
       <?php endif; ?>
       <?php endif; ?>
       
       
        <?php  if($this->estado == '5'): //4?>       
        <div class="row alert-danger2 alertrojo" >
            <div class="col-xs-12 text-center espace-bottom"> ERROR : <b>CAJA NO CERRADA</b></div>
              <div class="row">                 
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                       
                        <label class="espacetitlebottom etitletit" style="font-size: 32px"><b>CODIGO CAJA:</b></label>
                        <label id="dni_id" style="font-size: 32px" ><?php echo  isset($this->caja) ? $this->caja->COD_CAJA: ''; ?></label>
                    </div>
                </div>               
         </div>
        </div>       
       <?php endif; ?>
                     
        <?php  if($this->estado == '6'): //4?>       
        <div class="row alert-danger2 alertrojo" >
            <div class="col-xs-12 text-center espace-bottom"> ERROR : <b>CODIGO DE CAJA NO EXISTE</b></div>
              <div class="row">                 
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                       
                        <label class="espacetitlebottom etitletit" style="font-size: 32px"><b>CODIGO CAJA:</b></label>
                        <label id="dni_id" style="font-size: 32px" ><?php echo $_REQUEST['txtCaja']?></label>
                    </div>
                </div>               
         </div>
        </div>       
       <?php endif; ?>       
       
        <?php  if($this->estado == '7'): //4?>       
        <div class="row  alert-success2 alert" >
            <div class="col-xs-12 text-center espace-bottom"><b>LA CAJA YA ESTA CERRADA</b></div>
              <div class="row">                 
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                       
                        <label class="espacetitlebottom etitletit" style="font-size: 32px"><b>CODIGO CAJA:</b></label>
                        <label id="dni_id" style="font-size: 32px" ><?php echo $_REQUEST['txtCaja']?></label>
                    </div>
                </div>               
         </div>
        </div>       
       <?php endif; ?>              
       
       
<?php  if($this->estado == '8'): //4?>       
        <div class="row  alert-success2 alert" >
            <div class="col-xs-12 text-center espace-bottom"><b>TODOS LOS PAQUETES DE LA SEDE: <?php echo isset($this->caja) ? $this->caja->SEDE: ''; ?>, YA ESTA INVENTARIADA</b></div>
              <div class="row">                 
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                       
                        <label class="espacetitlebottom etitletit" style="font-size: 32px"><b>CODIGO CAJA:</b></label>
                        <label id="dni_id" style="font-size: 32px" ><?php echo $_REQUEST['txtCaja']?></label>
                    </div>
                </div>               
         </div>
        </div>       
       <?php endif; ?>                     
       
       <?php if($this->estado == '3'): //3?>
        <div class="row alert-danger2 alert" >
            <div class="col-xs-12 text-center espace-bottom">                 
                ERROR: <b>PAQUETE YA FUE INVENTARIADO</b>
           </div>
            <div class="row">
          <table class="table">
              <tr>
                  <td colspan="2"> <label class="etitletit"><b>CODIGO PAQUETE:</b></label>                      
                    <label id="dni_id" style="font-size:24px"><?php echo ($this->paquete) ? $this->paquete->COD_PAQUETE : ''; ?></label>               
                  </td> 
                  
                    <td rowspan="2" align="center">
                    <div class="aulasnro">
                    CAJA <br>               
                         <label id="dni_id" style="font-size: 62px;">
                         <b><?php echo ($this->paquete) ? $this->paquete->CAJA : ''; ?></b></label>
                    </div> 
              </td>
             </tr>
             <tr>
                 <td class="nowrap">
             <label id="dni_id" style="font-size: 32px">
           <?php echo ($this->paquete) ? $this->paquete->COD_MANUAL.' '. $this->paquete->MANUAL : ''; ?></label>
             </td>
             </tr>
             <tr>
                 <td class="nowrap">
                      <label class="etitletit"><b>SEDE:</b></label>
               <label id="dni_id" style="font-size:24px"><?php echo ($this->paquete) ? $this->paquete->SEDE : ''; ?></label>
                 </td>
             </tr>
           </table>

            </div>
               
        </div>
       <?php endif; ?>
      
       
                            <?php 
                            if(isset($this->paquetes_sin_inventariar)){
                                $i = 0;
                                $nro_registros = count($this->paquetes_sin_inventariar);
                                
                            if($nro_registros > 0) {                                
                            ?>
       
       <table  class="table table-bordered etableeli text-center table-striped" >
           <thead>
               <tr class="info">
                   <td colspan="4" style="text-align: left; font-size: 17px;" ><b>SEDE: <?php echo  isset($this->caja) ? $this->caja->SEDE: ''; ?></b></td>
               </tr>
               <tr class="info">
                   <td colspan="4" style="text-align: left;" ><b>PAQUETES QUE FALTAN INVENTARIAR</b></td>
               </tr>
           <tr class="info">
               <th>NRO.</th>
               <th>COD. PAQUETE</th>
               <th>MANUAL</th>
               <th>COD. MANUAL</th>                              
           </tr>
           </thead>
           <tbody>
           
                            <?php foreach ($this->paquetes_sin_inventariar as $item): ?>                                   
           <tr>
               
               <td><?php $i++; echo $i; ?></td>
               <td><?php echo $item->COD_PAQUETE; ?></td>
               <td><?php echo $item->MANUAL; ?></td>
               <td><?php echo $item->COD_MANUAL; ?></td>
                              
                    
               </tr>
                                <?php endforeach; ?>
               </tbody>
                            <?php } 
?>
           </table>
    <?php                            
                            
                            }
                            ?>
   </div>

</form>    
                                
            </div>
        </div>

</div>
<?php  if(isset($this->paquetes_de_caja) && count($this->paquetes_de_caja ) > 0){ ?> 
 <div id="myModal" class="modal fade" role="dialog">
                <div class="modal-dialog">

                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title"><label id="tipoo2"></label> REGISTRO DEL PESO DE LA CAJA <b> N°: <?php echo $this->caja->COD_CAJA; ?></b> </h4> 
                    </div>
                    <div class="modal-body">
                      <table class="table table-bordered etableeli text-center table-striped" id="nopistola"> 

                          <tbody>
                              <tr>
                                  <th class="info" style="text-align: center;">CAJA N°: <?php echo $this->caja->COD_CAJA;
                           ?> <br/>(En Kg)</th>
                                  <td><input type="number" id="txtPeso"  name="txtPeso" required class="form-control text-left input-buscador" type="number" placeholder="Ingrese peso de la caja" /></td>
                                  <td>
                                      <button class="btn btn-primary  input-buscador" onclick="cerrar_caja('<?php  echo $this->cod_sede; ?>','<?php echo $this->caja->COD_CAJA;
                           ?>')" style="color: #FFF;background-color: #446baf;border: 1px solid #0936af;" >GUARDAR</button>
                                  </td>
                              </tr>

                          </tbody>
                      </table>
                        
                        
                        
                        
                        <br/>
                        <table  class="table table-bordered etableeli text-center table-striped" >
           <thead>
               <tr class="info">
                   <td colspan="4" style="text-align: left;" ><b>Paquetes Inventariados</b></td>
               </tr>
           <tr class="info">
               <th>NRO.</th>
               <th>COD. PAQUETE</th>
               <th>MANUAL</th>
               <th>COD. MANUAL</th>                              
           </tr>
           </thead>
           <tbody>
           
               
                            <?php 
//                            {
                            foreach ($this->paquetes_de_caja as $item): ?>                                   
           <tr> 
               
               <td><?php $i++; echo $i; ?></td>
               <td><?php echo $item->COD_PAQUETE; ?></td>
               <td><?php echo $item->MANUAL; ?></td>
               <td><?php echo $item->COD_MANUAL; ?></td>
                              
                    
               </tr>
                                <?php endforeach;
//                            }
                            ?>
               </tbody>                            
           </table>
                        
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>                      
                    </div>
                  </div>

                </div>
              </div>       


<?php } ?>


 
