<?php
$this->form->CODIGO_BARRA->class = 'form-control text-left input-buscador';
$this->form->CODIGO_BARRA->placeholder = 'Pasar Lector de C&oacute;digo de Barra';
?>
<div class="container">

    <div class="panel panel-ecustom ui-shadow">
        <div class="panel-heading etitleprin"><?php echo 'SEDE: ' . ($this->_request->session('sede')) . ' / LOCAL: ' . $this->_request->session('nlocal'); ?></div>
        <div class="panel-body etitle">
            <input type="hidden" name="vjson" id ="vjson" value='<?php echo $this->form->getJsonValidate(TRUE); ?>'>
            <form class="form-signin" role="form" action="<?php echo BASE_URL; ?>index.php/local/local_01" method="GET" id="frmtcobarra_id" name="frmtcobarra">
                <!--INICIO -- Siempre estará-->
                <div class="row">
                    <div class="col-xs-12 espace-top espace-bottom buscador">
                        <div class="input-group">
                            <?php echo form_input($this->form->CODIGO_BARRA); ?>
                            <span class="input-group-btn">
                                <button class="btn btn-primary  input-buscador " type="submit">Buscar</button>
                            </span>
                        </div>
                    </div>
                </div>
                <!--FINAL -- Siempre estará-->
                
                
                
                           
                
                <?php if($this->estado == 3): ?> 
                
                  <div class="row  alert-success2 alert">

                            <div class="row">
                                <table  class="table">  
                                    <tr>
                                        <td colspan="2" style="font-size: 24px">
                                            <label class="etitletit"> <b>C&Oacute;DIGO DE BARRA:</b> </label>
                                            <label id="dni_id"><?php echo ($this->director) ? $this->director->CODIGO_BARRA : ''; ?></label>&nbsp;&nbsp;&nbsp
                                            <!--<label id="status_id" class="etitletit">(<?php // echo ($this->director) ? $this->director->ESTADO + 1 : ''; ?>)</label>-->
                                        </td> 
                                    </tr>
                                <tr>
                                        <td class="nowrap" colspan="2"  style="font-size: 24px">  
                                            <label id="name_id"><?php
                                                if ($this->director) {
                                                    if ($this->director->ORDEN_CAJA == 90) {
                                                        echo '<label class="etitletit" ><b>Tipo de caja: </b></label> CAJA ADICIONAL';
                                                    } else {
                                                        if ($this->director->ORDEN_CAJA == 99) {
                                                            echo '<label class="etitletit" ><b>Tipo de caja: </b></label> CANDADO';
                                                        } else {
                                                            echo '<label class="etitletit" ><b> Tipo de caja:</b> </label> CAJA DE APLICACION ' ;
                                                        }
                                                    }
                                                } else {
                                                    echo '';
                                                }
                                                ?>
                                            </label>
                                        </td>
                                    </tr>
                                <tr>
                                    <td colspan="2" style="font-size: 24px">
                                        <label class="etitletit"> <b>Lado de la caja:</b> </label>
                                        <label id="dni_id"><?php echo ($this->director) ? $this->director->LADO_ETIQUETA : ''; ?></label>                                       
                                    </td> 
                                </tr>                                                                        
                                    <tr> 
                                        <td colspan="2"> <div class="etitletit"><b>Sede Operativa :</b></div></td>                                    
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->SEDE : ''; ?></label>
                                        </td>
                                    </tr> 

                                    <tr> 
                                        <td colspan="2"> <div class="etitletit"><b>Local de Ubicaci&oacute;n :</b></div></td>                                    
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->NOMBRE_LOCAL : ''; ?></label>
                                        </td>
                                    </tr> 
                                </table>
                            </div>
                        </div>
                <?php endif;?>                
                
                <?php if($this->estado == 4): ?> 
                <div class="row espacerightleft alert-danger2 alert" style="<?php echo ($this->director) ? '' : 'display:none'; ?>">
                            <div class="col-xs-12 text-center espace-bottom" >  ERROR:<b> C&Oacute;DIGO DE BARRA DUPLICADO.</b></div>
                            <div class="row">
                                <table class="table">
                                    <tr>
                                        <td colspan="2" style="font-size: 24px"> 
                                            <label class="etitletit">
                                                <b>C&Oacute;DIGO DE BARRA :</b> </label>
                                            <label id="dni_id"> <?php echo ($this->director) ? $this->director->CODIGO_BARRA : ''; ?> </label></td>
                                    </tr>
                                <tr>
                                        <td class="nowrap" colspan="2"  style="font-size: 24px">  
                                            <label id="name_id"><?php
                                                if ($this->director) {
                                                    if ($this->director->ORDEN_CAJA == 90) {
                                                        echo '<label class="etitletit" ><b>Tipo de caja: </b></label> CAJA ADICIONAL';
                                                    } else {
                                                        if ($this->director->ORDEN_CAJA == 99) {
                                                            echo '<label class="etitletit" ><b>Tipo de caja: </b></label> CANDADO';
                                                        } else {
                                                            echo '<label class="etitletit" ><b> Tipo de caja:</b> </label> CAJA DE APLICACION ' ;
                                                        }
                                                    }
                                                } else {
                                                    echo '';
                                                }
                                                ?>
                                            </label>
                                        </td>
                                    </tr>
                                     <tr>
                                    <td colspan="2" style="font-size: 24px">
                                        <label class="etitletit"> <b>Lado de la caja:</b> </label>
                                        <label id="dni_id"><?php echo ($this->director) ? $this->director->LADO_ETIQUETA : ''; ?></label>                                       
                                    </td> 
                                    <tr>
                                        <td colspan="2" class="nowrap"> 
                                            <label class="espacetitlebottom etitletit"><b>Fecha de registro:</b></label>
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->FECHA : ''; ?></label>
                                        </td>
                                    </tr>
                                    <tr>                                        
                                        <td colspan="2" class="nowrap"> 
                                            <label class="espacetitlebottom etitletit"><b>Sede Operativa :</b></label>
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->SEDE : ''; ?></label>
                                        </td>                                                                                
                                    </tr> 
                                    <tr> 
                                        <td colspan="2" class="nowrap"> 
                                            <label class="espacetitlebottom etitletit"><b>Local de Ubicaci&oacute;n :</b></label>
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->NOMBRE_LOCAL : ''; ?></label>
                                        </td>                                          
                                    </tr>                                    
                                </table>
                            </div>
                        </div>
                <?php endif;?>             
                
                <?php if($this->estado == 5): ?> 
                <div class="row espacerightleft"> 
                        <div class="row  alert-danger2 alertrojo text-center" 
                             <label id="searchdni_id" class="etitle">CAJA NO REGISTRADA EN EL PADR&Oacute;N</label>
                        </div>
                    </div>
                <?php endif;?>
                
                
                <?php if ($this->estado == 6) : ?>
                
                
                        <div class="row espacerightleft alert-danger2 alert" style="<?php echo ($this->director) ? '' : 'display:none'; ?>">
                            <div class="col-xs-12 text-center espace-bottom" >  ERROR:<b> DEBE ESCANEAR EL LADO 1</b></div>
                            <div class="row">
                                <table class="table">
                                    <tr>
                                        <td colspan="2" style="font-size: 24px"> 
                                            <label class="etitletit">
                                                <b>C&Oacute;DIGO DE BARRA :</b> </label>
                                            <label id="dni_id"> <?php echo ($this->director) ? $this->director->CODIGO_BARRA : ''; ?> </label></td>
                                    </tr>
                                <tr>
                                        <td class="nowrap" colspan="2"  style="font-size: 24px">  
                                            <label id="name_id"><?php
                                                if ($this->director) {
                                                    if ($this->director->ORDEN_CAJA == 90) {
                                                        echo '<label class="etitletit" ><b>Tipo de caja: </b></label> CAJA ADICIONAL';
                                                    } else {
                                                        if ($this->director->ORDEN_CAJA == 99) {
                                                            echo '<label class="etitletit" ><b>Tipo de caja: </b></label> CANDADO';
                                                        } else {
                                                            echo '<label class="etitletit" ><b> Tipo de caja:</b> </label> CAJA DE APLICACION ' ;
                                                        }
                                                    }
                                                } else {
                                                    echo '';
                                                }
                                                ?>
                                            </label>
                                        </td>
                                    </tr>
                                     <tr>
                                    <td colspan="2" style="font-size: 24px">
                                        <label class="etitletit"> <b>Lado de la caja:</b> </label>
                                        <label id="dni_id"><?php echo ($this->director) ? $this->director->LADO_ETIQUETA : ''; ?></label>                                       
                                    </td> 
                                    <tr>                                        
                                        <td colspan="2" class="nowrap"> 
                                            <label class="espacetitlebottom etitletit"><b>Sede Operativa :</b></label>
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->SEDE : ''; ?></label>
                                        </td>                                                                                
                                    </tr> 
                                    <tr> 
                                        <td colspan="2" class="nowrap"> 
                                            <label class="espacetitlebottom etitletit"><b>Local de Ubicaci&oacute;n :</b></label>
                                            <label id="local_id"><?php echo ($this->director) ? $this->director->NOMBRE_LOCAL : ''; ?></label>
                                        </td>                                          
                                    </tr>        
                                </table>
                            </div>
                        </div>

                    <?php endif; ?>                

            </form>


<!--            <input type="hidden" name="nro_local" id="nro_local_id" value="<?php // echo ($this->director) ? $this->director->nro_local : ''; ?>"/>
            <input type="hidden" id="ins_numdoc_id" name="ins_numdoc" value="<?php // echo ($this->director) ? $this->director->ins_numdoc : ''; ?>"/>
            <input type="hidden" id="codigo_id" name="codigo_id" value="<?php // echo ($this->director) ? $this->director->codigo : ''; ?>"/>
            <input type="hidden" id="estado_id" name="estado" value="<?php // echo ($this->estado) ? $this->estado : ''; ?>"/>-->
        </div>

    </div>
</div>