<!DOCTYPE html>
<html lang="en-us" id="lock-page">
	<head>
		<meta charset="utf-8">
		<title> <?= APP_NAME; ?></title>
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<!-- #CSS Links -->
		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/font-awesome.min.css">

		<!-- SmartAdmin Styles : Caution! DO NOT change the order -->
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-production-plugins.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-production.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-skins.min.css">

		<!-- SmartAdmin RTL Support -->
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-rtl.min.css"> 

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css"> -->

		<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/demo.min.css">

		<!-- page related CSS -->
		<link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/lockscreen.min.css">

		<!-- #FAVICONS -->
		<link rel="shortcut icon" href="<?= BASE_URL; ?>public/img/favicon/favicon.ico" type="image/x-icon">
		<link rel="icon" href="<?= BASE_URL; ?>public/img/favicon/favicon.ico" type="image/x-icon">

		<!-- #GOOGLE FONT -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

		<!-- #APP SCREEN / ICONS -->
		<!-- Specifying a Webpage Icon for Web Clip 
			 Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
		<link rel="apple-touch-icon" href="<?= BASE_URL; ?>public/img/splash/sptouch-icon-iphone.png">
		<link rel="apple-touch-icon" sizes="76x76" href="<?= BASE_URL; ?>public/img/splash/touch-icon-ipad.png">
		<link rel="apple-touch-icon" sizes="120x120" href="<?= BASE_URL; ?>public/img/splash/touch-icon-iphone-retina.png">
		<link rel="apple-touch-icon" sizes="152x152" href="<?= BASE_URL; ?>public/img/splash/touch-icon-ipad-retina.png">
		
		<!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		
		<!-- Startup image for web apps -->
		<link rel="apple-touch-startup-image" href="<?= BASE_URL; ?>public/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
		<link rel="apple-touch-startup-image" href="<?= BASE_URL; ?>public/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
		<link rel="apple-touch-startup-image" href="<?= BASE_URL; ?>public/img/splash/iphone.png" media="screen and (max-device-width: 320px)">

	</head>
	
	<body>

		<div id="main" role="main">

			<!-- MAIN CONTENT -->

			<form class="lockscreen animated flipInY">
				<div class="logo">
					<h1 class="semi-bold"><img src="<?= BASE_URL; ?>public/img/logo-o.png" alt="<?= APP_NAME; ?>" /> <?= APP_NAME; ?></h1>
				</div>
				<div>
					<img src="<?= BASE_URL; ?>public/img/avatars/sunny-big.png" alt="" width="120" height="120" />
					<div>
						<h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile"></i><?= $_SESSION["NAME"] ?> <small><i class="fa fa-lock text-muted"></i> &nbsp;Locked</small></h1>
						<p class="text-muted">
							<a href="mailto:simmons@smartadmin">john.doe@smartadmin.com</a>
						</p>

						<div class="input-group">
							<input class="form-control" type="hidden" id="usuarioId" value="<?= $this->usuarioId; ?>">
							<input class="form-control" type="hidden" id="ubicacion" value="<?= BASE_URL."user/unlock" ?>">
							<input class="form-control" type="password" id="password" placeholder="Password">
							<div class="input-group-btn">
								<a class="btn btn-primary" id="btnLogin">
									<i class="fa fa-key"></i>
								</a>
							</div>
						</div>
						<p class="no-margin margin-top-5">
							No es usted? <a href="<?= BASE_URL; ?>user/logout"> Click aqu&iacute;</a>
						</p>
					</div>
				</div>
				<p class="font-xs margin-top-5">
					Copyright <?= APP_NAME; ?> 2016-2020.
				</p>
			</form>

		</div>

		<!--================================================== -->	

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
		<script src="<?= BASE_URL; ?>public/js/plugin/pace/pace.min.js"></script>

	    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
	    <script src="<?= BASE_URL; ?>public/js/libs/jquery-2.1.1.min.js"></script>

	    <script src="<?= BASE_URL; ?>public/js/libs/jquery-ui-1.10.3.min.js"></script>

		<!-- IMPORTANT: APP CONFIG -->
		<script src="<?= BASE_URL; ?>public/js/app.config.js"></script>

		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events 		
		<script src="js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->		
		<script src="<?= BASE_URL; ?>public/js/bootstrap/bootstrap.min.js"></script>

		<!-- JQUERY VALIDATE -->
		<script src="<?= BASE_URL; ?>public/js/plugin/jquery-validate/jquery.validate.min.js"></script>
		
		<!-- JQUERY MASKED INPUT -->
		<script src="<?= BASE_URL; ?>public/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
		
		<!--[if IE 8]>
			
			<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
			
		<![endif]-->

		<!-- MAIN APP JS FILE -->
		<script src="<?= BASE_URL; ?>public/js/app.min.js"></script>
		
		<? if(isset($_layoutParams['js']) && count($_layoutParams['js'])): ?>
	      <? foreach($_layoutParams['js'] as $layout): ?>
	        <script src="<?= $layout ?>" type="text/javascript"></script>
	      <? endforeach; ?>
	    <? endif; ?>

	</body>
</html>