
<div class="container">
    <div class="panel panel-ecustom ui-shadow">
        <div class="panel-heading etitleprin"><b> <?php echo 'SEDE: '.($this->_request->session('sede')).' / LOCAL: '.$this->_request->session('nlocal'); ?></b></div>
            <div class="panel-body etitle">
                
                <form class="form-signin" role="form" action="<?php echo BASE_URL; ?>index.php/aula" method="GET" id="frmauladirector" name="frmauladirector">
                    <div class="row"> 
                        <div class="form-group  espacerightleft">
                       
                        <span class="espacetitlebottom etitletit"><b>Aula</b></span>
                            <select class="form-control" id="paulas_id" required name="paulas" >
                                <option value="">Seleccione</option>
                                  <?php foreach ($this->aulas as $aula): ?>
                                <?php if ($aula->naula!==999): ?>
                                <option value="<?php echo $aula->naula; ?>"
                                    <?php if(isset($_GET['paulas'])): 
                                            if($_GET['paulas'] == $aula->naula) : 
                                                echo 'selected' ; 
                                            endif; 
                                          endif;?> >  <?php echo $aula->nombre;  if($aula->tipo==0):echo ' (Contingencia)' ;endif; ?></option>
                                <?php endif; ?>
                                <?php endforeach; ?>                                
                            </select>
                        </div>
                    </div>
            <div class="row">
                <div class="col-xs-12 espace-top espace-bottom buscador">
                   
                    <div class="input-group">
                       <input id="ins_numdoc" required class="form-control text-left input-buscador" type="number" placeholder="Pasar Lector de Código de Barra" data-length="" value="" name="ins_numdoc">
                        <span class="input-group-btn">
                            <button class="btn btn-primary  input-buscador " type="submit">Buscar</button>
                        </span>
                    </div>
                </div>
            </div>

   <div class="row espacerightleft" >
       
       <?php  if($this->estado == '1'): //1?>
        <div class="row  alert-success2 alert" >
              <div class="row">
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">
                       
                        <label class="espacetitlebottom etitletit"><b>DNI : </b></label>
                        <label id="dni_id" style="font-size:24px;"><?php echo ($this->director) ? $this->director->ins_numdoc : ''; ?></label>
                    </div>
                </div>
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">                   
                       
                        <label id="dni_id" style="font-size:32px;"><?php echo ($this->director) ? $this->director->apepat.' '. $this->director->apemat .' '. $this->director->nombres : ''; ?></label>
                    </div>
                </div>

         </div>
        </div>
       <?php endif; ?>
       <?php if($this->estado == '6'):    ?>   
    <div class="row alert   <?php if($this->director->nro_local === $this->_request->session('nro_local')): echo 'alert-success';else: echo 'alert-warning'; endif; ?>" style="<?php echo ($this->director) ? '' : 'display:none'; ?>">
      
        <div class="col-xs-12 text-center espace-bottom"> ERROR: <b>SU LOCAL DE EVALUACI&Oacute;N ES.</b> </div>
        <div class="row">


                          <table class="table">
                                <tr>
                                    <td colspan="2" class="nowrap"> 
                                    <label class="etitletit">
                                <b>Sede :</b> </label>
                                <label id="dni_id"><?php echo ($this->director) ? $this->director->sede : ''; ?></label>
                                </td>
                               <td rowspan="5" class="text-center">
                              <div class="aulasnro">
                                     AULA <br>
                                 <label id="aula_id" style="font-size: 92px;">
                                            
                                    <b> <?php echo ($this->director) ? $this->director->aula : ''; ?> </b></label>
                                 </div>
                                </td>
                                  </tr>
                                 <tr>
                                  <td colspan="2"><div class="etitletit"><b>Local de aplicaci&oacute;n :</b></div> </td>
                                 </tr>
                                  <tr>
                                     <td colspan="2">
                                         <label id="local_id"><?php echo ($this->director) ? $this->director->local_aplicacion : ''; ?></label>
                                     </td>
                                 </tr>
                                 <tr>
                                 <td colspan="2">
                                 <label class="espacetitlebottom etitletit"><b>Direcci&oacute;n :</b></label>
                                 </td>
                                 </tr>
                                 <tr>
                                     <td colspan="2">
                                         <label id="aula_id"><?php echo ($this->director) ? $this->director->direccion : ''; ?></label>
                                       </td>
                                 </tr>                         
                                </table> 
        </div>
    </div>  
    
    
    <?php endif; ?>
       
       
       <?php  if($this->estado == '4'): //4?>
        <div class="row alert-danger2 alertrojo" >
            <div class="col-xs-12 text-center espace-bottom"> ERROR : <b>POSTULANTE NO ENCONTRADO EN EL PADR&Oacute;N.</b></div>
              <div class="row">
                 
                <div class="col-xs-12"> 
                    <div class="form-group  espacerightleft espace-top">
                       
                        <label class="espacetitlebottom etitletit" style="font-size: 32px"><b>DNI : </b></label>
                        <label id="dni_id"><?php echo $_REQUEST['ins_numdoc']?></label>
                    </div>
                </div>
                

         </div>
        </div>
       <?php endif; ?>
       
       <?php if($this->estado == '2'): //2?>
        <div class="row alert-danger2 alert" >
            <div class="col-xs-12 text-center espace-bottom"> ERROR: <b>SU AULA DE EVALUACI&Oacute;N ES.</b> </div>
            <div class="row">
             <table class="table">
         <tr>
         <td> <label class="etitletit"><b>DNI :</b></label>
         <label id="dni_id" style="font-size:24px"><?php echo ($this->director) ? $this->director->ins_numdoc : ''; ?></label>
            </td>
          <td rowspan="2" class="text-center">
          <div class="aulasnro">
          AULA <br>
          <label id="dni_id" style="font-size: 92px;">
              <b> <?php echo ($this->director) ? $this->director->aula : ''; ?></b></label>
          </div>
         </td>
          </tr> 
         <tr>
             <td class="nowrap">
         <label id="dni_id" style="font-size: 32px"><?php echo ($this->director) ? $this->director->apepat . ' ' . $this->director->apemat . ' ' . $this->director->nombres : ''; ?></label> 
         </td>                                        
          </tr>
        </table>

            </div>               
        </div>
       <?php endif; ?>
       
       
       <?php if($this->estado == '3'): //3?>
        <div class="row alert-danger2 alert" >
            <div class="col-xs-12 text-center espace-bottom"> 
                ERROR: <b>POSTULANTE YA REGISTR&Oacute; SU ASISTENCIA.</b>
           </div>
            <div class="row">
          <table class="table">
              <tr>
                  <td colspan="2"> <label class="etitletit"><b>DNI :</b></label>
               <label id="dni_id" style="font-size:24px"><?php echo ($this->director) ? $this->director->ins_numdoc : ''; ?></label>
              </td> 
              <td rowspan="2" align="center">
              <div class="aulasnro">
              AULA <br>
               <label id="dni_id" style="font-size: 92px;">
                   <b><?php echo ($this->director) ? $this->director->new_aula : ''; ?></b></label>
              </div> 
              </td>
             </tr>
             <tr>
                 <td class="nowrap">
             <label id="dni_id" style="font-size: 32px">
            <?php echo ($this->director) ? $this->director->apepat . ' ' . $this->director->apemat . ' ' . $this->director->nombres : ''; ?></label>
             </td>
             </tr>
           </table>

            </div>
               
        </div>
       <?php endif; ?>
       
   </div>
                    
                    
                    
            

            

</form>    
                
                
      <input type="hidden" name="nro_local" id="nro_local_id" value="<?php echo ($this->director) ? $this->director->nro_local : ''; ?>"/>
        <input type="hidden" id="ins_numdoc_id" name="ins_numdoc" value="<?php echo ($this->director) ? $this->director->ins_numdoc : ''; ?>"/>
        <input type="hidden" id="estado_id" name="estado" value="<?php echo ($this->estado) ? $this->estado : ''; ?>"/>         
            <input type="hidden" id="codigo_id" name="codigo_id" value="<?php echo ($this->director) ? $this->director->codigo : ''; ?>"/>      
                                    
                                
            </div>
        </div>

</div>