
<!DOCTYPE html>
<html lang="en-us" id="extr-page">
    <head>
        <meta charset="utf-8">
        <title> <?= APP_NAME; ?></title>
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <!-- #CSS Links -->
        <!-- Basic Styles -->
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/font-awesome.min.css">

        <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-production-plugins.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-production.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-skins.min.css">

        <!-- SmartAdmin RTL Support -->
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/smartadmin-rtl.min.css"> 

        <!-- We recommend you use "your_style.css" to override SmartAdmin
             specific styles this will also ensure you retrain your customization with each SmartAdmin update.
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/your_style.css"> -->

        <!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
        <link rel="stylesheet" type="text/css" media="screen" href="<?= BASE_URL; ?>public/css/demo.min.css">

        <!-- #FAVICONS -->
        <link rel="shortcut icon" href="<?= BASE_URL; ?>public/img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" href="<?= BASE_URL; ?>public/img/favicon/favicon.ico" type="image/x-icon">

        <!-- #GOOGLE FONT -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

        <!-- #APP SCREEN / ICONS -->
        <!-- Specifying a Webpage Icon for Web Clip 
                 Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
        <link rel="apple-touch-icon" href="<?= BASE_URL; ?>public/img/splash/sptouch-icon-iphone.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?= BASE_URL; ?>public/img/splash/touch-icon-ipad.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?= BASE_URL; ?>public/img/splash/touch-icon-iphone-retina.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?= BASE_URL; ?>public/img/splash/touch-icon-ipad-retina.png">

        <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <!-- Startup image for web apps -->
        <link rel="apple-touch-startup-image" href="<?= BASE_URL; ?>public/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
        <link rel="apple-touch-startup-image" href="<?= BASE_URL; ?>public/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
        <link rel="apple-touch-startup-image" href="<?= BASE_URL; ?>public/img/splash/iphone.png" media="screen and (max-device-width: 320px)">

    </head>

    <body class="animated fadeInDown">
        <header id="header">
            <div id="logo-group">
                    <span id="logo"> <img src="<?= BASE_URL; ?>public/img/logo.png" alt="<?= APP_NAME; ?>"> </span>
            </div>
        </header>
            <div id="main" role="main">
                <!-- MAIN CONTENT -->
                <div id="content" class="container">
                    <div class="row">
                        <div class="col-sm-4 col-md-offset-4">
                            <div class="well">
                                <form action="<?php echo BASE_URL; ?>index.php/auth/auth/validar" class="smart-form client-form"  method="POST" id="frmlogin" name="frmlogin">
                                    <header>
                                            Ingrese sus Credenciales
                                    </header>
                                    <fieldset>
                                        <section>
                                            <label class="label">Clave</label>
                                            <label class="input"> <i class="icon-append fa fa-lock"></i>
                                            <input type="password" class="form-control"  
                                                   name="frmlogin[clave]" placeholder="Ingresar Clave"  value="INVMON1">
                                            <b class="tooltip tooltip-top-right">
                                                <i class="fa fa-lock txt-color-teal"></i> Por favor ingrese su Clave</b> 
                                            </label>
                                        </section>                                       
                                    </fieldset>
                                    <footer>
                                        <button type="submit" class="btn btn-primary">
                                            Ingresar
                                        </button>
                                    </footer>
                                </form>
                                <div class="text-center espace-bottom text-info">
                                    <b>Ingresar la clave del local</b><br>
                                    <b><?php echo sprintf($this->evento); ?></b><br>
                                    <b><?php echo sprintf('Versión %s' , $this->version ); ?></b>
                                </div>
                            </div>											
                        </div>
                    </div>
                </div>
            </div>

            <!--================================================== -->	

            <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
            <script src="<?= BASE_URL; ?>public/js/plugin/pace/pace.min.js"></script>

        <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script> if (!window.jQuery) { document.write('<script src="<?= BASE_URL; ?>public/js/libs/jquery-2.1.1.min.js"><\/script>');} </script>

        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
            <script> if (!window.jQuery.ui) { document.write('<script src="<?= BASE_URL; ?>public/js/libs/jquery-ui-1.10.3.min.js"><\/script>');} </script>

            <!-- IMPORTANT: APP CONFIG -->
            <script src="<?= BASE_URL; ?>public/js/app.config.js"></script>

            <!-- JS TOUCH : include this plugin for mobile drag / drop touch events 		
            <script src="<?= BASE_URL; ?>public/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

            <!-- BOOTSTRAP JS -->		
            <script src="<?= BASE_URL; ?>public/js/bootstrap/bootstrap.min.js"></script>

            <!-- JQUERY VALIDATE -->
            <script src="<?= BASE_URL; ?>public/js/plugin/jquery-validate/jquery.validate.min.js"></script>

            <!-- JQUERY MASKED INPUT -->
            <script src="<?= BASE_URL; ?>public/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

            <!--[if IE 8]>

                    <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

            <![endif]-->

            <!-- MAIN APP JS FILE -->
            <script src="<?= BASE_URL; ?>public/js/app.min.js"></script>

            <script type="text/javascript">
                    runAllForms();

                    $(function() {
                            // Validation
                            $("#frmlogin").validate({
                                    // Rules for form validation                                   
                                    rules : {
//                                            email : {
//                                                    required : true
//                                            },
                                            frmlogin[clave] : {
                                                    required : true,
                                                    minlength : 3,
                                                    maxlength : 20
                                            }
                                    },

                                    // Messages for form validation
                                    messages : {
//                                            email : {
//                                                    required : 'Ingrese su Usuario'
//                                            },
                                            password : {
                                                    required : 'Ingrese su Clave'
                                            }
                                    },

                                    // Do not change code below
                                    errorPlacement : function(error, element) {
                                            error.insertAfter(element.parent());
                                    }
                            });
                    });
            </script>

    </body>
</html>








