<section id="seccion2" class="clearfix">
    <div class="panel panel-ecustom ui-shadow">
        <div class="panel-heading esubtitle">Configuración WI-FI</div>
        <div class="panel-body">
            <section class="espace">
                <div class="table-responsive">
                    <table id="tbl6" class="table table-striped table-bordered table-hover table-condensed  etableeli etitle ecenter" >
                        <tr>
                            <td>
                                <select id="wificonf">
                                    <option value="1" <?php echo $this->config->valor === '1' ? 'selected' : '';  ?> >INEI</option>
                                    <option value="2" <?php echo $this->config->valor === '2' ? 'selected' : '';  ?>>EXTERNO</option>
                                </select>
                                <input type="button" id="btn_config" class="btn btn-primary" data-loading-text="Aplicando cambios. espere por favor." value="Aplicar" />
                                
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span id="result_update"></span>
                            </td>
                        </tr>
                        
                    </table>
                </div>
            </section>
        </div>
    </div>
    
</section>
</form>