<section id="seccion2" class="clearfix">
    <div class="panel panel-ecustom ui-shadow">
        <div class="panel-heading esubtitle">Actualización del Sistema (En Línea)</div>
        <div class="panel-body">
            <section class="espace">
                <div class="table-responsive">
                    <table id="tbl6" class="table table-striped table-bordered table-hover table-condensed  etableeli etitle ecenter" >
                        <tr>
                            <td>
                                <input type="button" id="btn-downApp" class="btn btn-primary" value="Descargar Actualización" />&nbsp;
                                <input type="button" id="btn-updateApp" class="btn btn-primary" value="Aplicar Actualización" />
                                
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span id="result_update"></span>
                            </td>
                        </tr>
                        
                    </table>
                </div>
            </section>
        </div>
    </div>
    
</section>
</form>