
<div id="container"><!--content del menu -->
    <div class="container-fluid etitle"> <!-- contenido fluid del boostrat-->

        <div class="panel panel-ecustom ui-shadow">
            <div class="panel-heading etitleprin">
                
                <DIV class="btn-news"><b><?php echo $this->titulo; ?> </b> </DIV>
                <div  class="btn-news"> 
                    <button type="button" class="emnbtnopt dropdown-toggle btn-new-position "
                            data-toggle="dropdown">
                        <a href="javascript:void(0);" onclick="_transfer('1');"><span class="glyphicon glyphicon-refresh"></span></a>
                    </button>
                </div>
            </div>
            
            <form role="form" action="" id="frm1">
                <div class="row eborderper">
                    <div class="col-xs-10 col-md-12 espace-top table-responsive text-center">
                        <table  class="table table-bordered etableeli text-center table-hover">
                            <thead><tr class="info">
                                    <td>C&Oacute;DIGO DE BARRA</td>
                                    <td>DESCRIPCI&Oacute;N</td>
                                    <td>FECHA Y HORA</td>  
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->directores as $director): ?>
                                    <tr  <?php echo ($director->estatus == '5') ? 'class="alert-success"' : 'class="alert-danger"'; ?>   >
                                        <td><small><?php echo $director->ins_numdoc; ?></small></td>
                                        
                                       <td class="text-left"><small><?php
//                                       echo 'ACL : ' .$director->apepat; 
                                       
                                        if($director){                                 
                                 if( $director->apepat == 90){
                                     echo 'CAJA ADICIONAL';
                                 }else{
                                     if( $director->apepat == 99){
                                         echo 'CANDADO';
                                     }else{
                                         if( $director->apepat > 0){
                                             echo 'ACL : ' .$director->apepat;
                                         }else{
                                             echo '';
                                         }                                         
                                     }
                                 }                                 
                             }else{
                                  echo '';
                             }
                                       ?></small></td>
                                        <td><small><?php echo $director->fecha_registro; ?></small></td>
                                         
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-xs-10">
                                <?php echo $this->paginator; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
    <span class="sr-only">45% Complete</span>
  </div>
</div>
<div class="modal-backdrop fade in"></div>-->

<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="modalMessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Sincronizando datos</h4>
      </div>
      <div class="modal-body">
          Espere por favor, este proceso puede tardar entre 15 y 40 segundos.
      </div>
    </div>
  </div>
</div>